import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const openAIApiKey = Deno.env.get('OPENAI_API_KEY');
    if (!openAIApiKey) {
      throw new Error('OPENAI_API_KEY is not set');
    }

    const { 
      destination, 
      startDate, 
      endDate, 
      budget, 
      travelStyle, 
      travelers, 
      preferences,
      conversationHistory 
    } = await req.json();

    console.log('AI Trip Planning request:', { destination, startDate, endDate, budget, travelStyle });

    // Build the AI prompt based on user inputs
    const systemPrompt = `You are JourneyXWave's AI travel assistant. Create detailed, personalized trip itineraries based on user preferences. 

    Always respond with a JSON structure containing:
    - title: A catchy trip title
    - summary: Brief overview of the trip
    - daily_itinerary: Array of daily plans with activities, times, locations, and estimated costs
    - total_estimated_cost: Overall budget breakdown
    - travel_tips: Helpful advice for the destination
    - packing_suggestions: Essential items to pack
    - best_season: When to visit
    - local_cuisine: Must-try dishes
    - safety_tips: Important safety information

    Be specific, practical, and consider local culture, weather, and logistics.`;

    const userPrompt = `Plan a ${Math.ceil((new Date(endDate).getTime() - new Date(startDate).getTime()) / (1000 * 60 * 60 * 24))} day trip to ${destination} from ${startDate} to ${endDate}.

    Details:
    - Budget: ₹${budget || 'Not specified'}
    - Travel style: ${travelStyle || 'Moderate'}
    - Number of travelers: ${travelers || 1}
    - Preferences: ${preferences || 'None specified'}

    ${conversationHistory ? `Previous conversation: ${conversationHistory}` : ''}

    Please create a comprehensive itinerary with daily activities, estimated costs, and practical travel advice.`;

    // Create conversation history for context
    const messages = [
      { role: 'system', content: systemPrompt },
      { role: 'user', content: userPrompt }
    ];

    console.log('Sending request to OpenAI...');

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${openAIApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'gpt-4o-mini',
        messages: messages,
        temperature: 0.7,
        max_tokens: 4000,
        response_format: { type: "json_object" }
      }),
    });

    if (!response.ok) {
      const errorData = await response.json();
      console.error('OpenAI API error:', errorData);
      throw new Error(`OpenAI API error: ${errorData.error?.message || 'Unknown error'}`);
    }

    const data = await response.json();
    console.log('OpenAI response received');

    const aiResponse = JSON.parse(data.choices[0].message.content);

    // Save the generated itinerary if trip data is provided
    if (destination && startDate && endDate) {
      const supabase = createClient(
        Deno.env.get('SUPABASE_URL') ?? '',
        Deno.env.get('SUPABASE_ANON_KEY') ?? ''
      );

      // Get user from auth header
      const authHeader = req.headers.get('Authorization');
      if (authHeader) {
        const { data: { user }, error: authError } = await supabase.auth.getUser(
          authHeader.replace('Bearer ', '')
        );

        if (user && !authError) {
          console.log('Saving generated itinerary for user:', user.id);
          
          // Create trip with AI-generated itinerary
          const { error: tripError } = await supabase
            .from('trips')
            .insert([{
              user_id: user.id,
              title: aiResponse.title || `Trip to ${destination}`,
              destination: destination,
              start_date: startDate,
              end_date: endDate,
              budget: budget ? parseFloat(budget) : null,
              status: 'planning',
              ai_generated_itinerary: aiResponse,
              notes: `Generated by AI • ${travelers} travelers • ${travelStyle} style`
            }]);

          if (tripError) {
            console.error('Error saving trip:', tripError);
          } else {
            console.log('Trip saved successfully');
          }
        }
      }
    }

    return new Response(
      JSON.stringify({
        success: true,
        itinerary: aiResponse,
        generatedAt: new Date().toISOString()
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );

  } catch (error) {
    console.error('Error in ai-trip-planner:', error);
    return new Response(
      JSON.stringify({ 
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error occurred',
        timestamp: new Date().toISOString()
      }),
      {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );
  }
});